// src/Views/MissingEmail/MissingEmail.jsx
import React, { useContext, useRef, useState, useEffect } from "react";
import AppContext from "../../Storage/AppContext";
import axios from "axios";
import { useNavigate } from "react-router-dom";
import { validateEmailRegex } from "../../utils/regexUtils";
import Form from "../../Components/Form/Form";
import config from "../../config/config";
import useNavigateWithCallback from "../../utils/useNavigateWithCallback";
import useValidateEmail from "../../utils/useValidateEmail";
import useUpdateUserData from "../../utils/useUpdateUserData";
import useValidateToken from "../../utils/useValidateToken";
import useHandleCloseSession from "../../utils/useHandleCloseSession";


const MissingEmail = () => {
	const context = useContext(AppContext);
	const emailRef = useRef(null);
	const navigate = useNavigate();
	const [error, setError] = useState(false);
	const [emailSent, setEmailSent] = useState(false);


	async function validateUserToken() {
		const isValidToken = await useValidateToken(context);
		if (!context.user_logged || !isValidToken) {
			useHandleCloseSession(context);
			useNavigateWithCallback(navigate, "/login");
		}
	}
	useEffect(() => {
		async function validateEmail() {
			if (window.location.href.includes(config.confirmemailLink) && emailSent) {
				const response = await useValidateEmail(context, window.location.href.split(config.confirmemailLink)[1]);
				if (response.result) {
					context.setModal({
						visible: true,
						message: "Email confirmado",
						status: "success",
						confirm: context.setModal({}),
					});
					setTimeout(() => {
						context.setModal({});
					}, 5000);
					useUpdateUserData(context, navigate)
				} else {
					context.setModal({
						visible: true,
						message: response.data,
						status: "error",
						confirm: context.setModal({}),
					});
					setTimeout(() => {
						context.setModal({});
					}, 5000);
					useNavigateWithCallback(navigate, "/missing-email");
				}
			}
		}
		validateEmail();
		if (context.user_logged?.email != null && !emailSent) {
			useNavigateWithCallback(navigate, "/app");
		}
	}, [emailSent]);

	useEffect(() => {
		if (context.user_logged) {
			validateUserToken();
			isEmailSent();
			if (context.user_logged?.email != null) {
				useNavigateWithCallback(navigate, "/app");
			}
		}

	}, [context.user_logged]);

	async function isEmailSent() {
		const mailResponse = await axios.get(`${config.baseUrl}users/validateEmailSent/${context.user_logged.id}`, {
			headers: {
				Accept: "application/json",
				Bearer: context.x_token,
			},
		}).then((response) => {
			return response;
		}).catch((error) => {
			return error
		})
		setEmailSent(mailResponse.data?.emailSent || false)
	}

	async function requestEmail(event) {
		event.preventDefault();
		if (
			!validateEmailRegex(emailRef.current.value, () =>
				setError({
					status: true,
					message:
						"Correo electrónico no válido",
				})
			)
		) {
			return false;
		}
		await axios
			.put(
				`${config.baseUrl}users/${context.user_logged?.id}`,
				{ email: emailRef.current.value },
				{
					headers: {
						Accept: "application/json",
						Bearer: context.x_token,
					},
				}
			)
			.then((response) => {
				if (response.status == 200) {
					context.setModal({
						visible: true,
						message: "Email de confirmación enviado",
						status: "success",
						confirm: context.setModal({}),
					});
					setTimeout(() => {
						context.setModal({});
					}, 5000);
					event.target.reset();
					setEmailSent(true)
				}
			})
			.catch((error) => {
				if (error.response.status == 404) {
					context.setModal({
						visible: true,
						message: "Usuario no encontrado",
						status: "error",
						confirm: context.setModal({}),
					});
					setTimeout(() => {
						context.setModal({});
					}, 5000);
				} else {
					context.setModal({
						visible: true,
						message: error.response.data.message,
						status: "error",
						confirm: context.setModal({}),
					});
					setTimeout(() => {
						context.setModal({});
					}, 5000);
				}
			});
	}

	return (
		<>

			<div className="container">
				{context.user_logged && (context.user_logged?.email == null ? !emailSent ?
					<div>
						<p style={{ textAlign: "center" }}>
							Tras la última actualización de la aplicación, se requiere que todos los usuarios registrados tengan una dirección de correo electrónico asociada
						</p>
						<p style={{ fontWeight: "bold", marginTop: "1rem", textAlign: "center" }}>
							Por lo que deberás introducir un email válido en el formulario más abajo para seguir usando la app 👇 Muchas gracias
						</p>
						<Form
							action={requestEmail}
							error={error}
							submitValue="Enviar"
							fields={[
								{
									name: "email",
									placeholder: "Correo electrónico",
									type: "email",
									ref: emailRef,
									required: true,
								},
							]}
						/>
					</div>
					: <div>
						<p style={{ textAlign: "center" }}>
							Revisa tu bandeja de entrada para confirmar tu correo.
						</p>
						<br></br>
						<p style={{ fontWeight: "bold", marginTop: "1rem", textAlign: "center" }}>Si no lo encuentras, revisa la bandeja de correo no deseado.</p>
					</div>
					: <div>
						<p style={{ textAlign: "center" }}>
							Actualización correcta, serás redirigido a la app automáticamente
						</p>
						<br></br>
						<p style={{ fontWeight: "bold", marginTop: "1rem", textAlign: "center" }}>Si no eres redirigido automáticamente, recarga la página</p>
					</div>)}
			</div>
		</>

	);
};

export default MissingEmail;

// src/views/MissingEmail/MissingEmail.vue
<script setup lang="ts">
import { ref, onMounted, watch } from 'vue'
import { useRouter } from 'vue-router'
import { useAppStore } from '../../stores/app'
import axios from 'axios'
import { validateEmailRegex } from '../../utils/regexUtils'
import Form from '../../components/Form/Form.vue'
import config from '../../config/config'
import useNavigateWithCallback from '../../composables/useNavigateWithCallback'
import useValidateEmail from '../../composables/useValidateEmail'
import useUpdateUserData from '../../composables/useUpdateUserData'
import useValidateToken from '../../composables/useValidateToken'
import useHandleCloseSession from '../../composables/useHandleCloseSession'

const store = useAppStore()
const router = useRouter()
const emailRef = ref<HTMLInputElement | null>(null)
const error = ref<any>(false)
const emailSent = ref(false)

async function validateUserToken() {
  const isValidToken = await useValidateToken(store)
  if (!store.userLogged || !isValidToken) {
    useHandleCloseSession(store)
    useNavigateWithCallback(router, '/login')
  }
}

watch(() => emailSent.value, async () => {
  if (window.location.href.includes(config.confirmemailLink) && emailSent.value) {
    const response = await useValidateEmail(store, window.location.href.split(config.confirmemailLink)[1])
    if (response.result) {
      store.setModal({
        visible: true,
        message: 'Email confirmado',
        status: 'success',
        confirm: store.setModal({}),
      })
      setTimeout(() => {
        store.setModal({})
      }, 5000)
      useUpdateUserData(store, router)
    } else {
      store.setModal({
        visible: true,
        message: response.data,
        status: 'error',
        confirm: store.setModal({}),
      })
      setTimeout(() => {
        store.setModal({})
      }, 5000)
      useNavigateWithCallback(router, '/missing-email')
    }
  }
  if ((store.userLogged as any)?.email != null && !emailSent.value) {
    useNavigateWithCallback(router, '/app')
  }
})

watch(() => store.userLogged, async () => {
  if (store.userLogged) {
    validateUserToken()
    await isEmailSent()
    if ((store.userLogged as any)?.email != null) {
      useNavigateWithCallback(router, '/app')
    }
  }
})

async function isEmailSent() {
  try {
    const mailResponse = await axios.get(
      `${config.baseUrl}users/validateEmailSent/${(store.userLogged as any)?.id}`,
      {
        headers: {
          Accept: 'application/json',
          Bearer: store.xToken,
        },
      },
    )
    emailSent.value = mailResponse.data?.emailSent || false
  } catch {
    emailSent.value = false
  }
}

async function requestEmail(event: Event) {
  event.preventDefault()
  if (
    !validateEmailRegex(emailRef.value?.value || '', () =>
      error.value = {
        status: true,
        message: 'Correo electrónico no válido',
      },
    )
  ) {
    return
  }
  error.value = false
  await axios
    .put(
      `${config.baseUrl}users/${(store.userLogged as any)?.id}`,
      { email: emailRef.value?.value },
      {
        headers: {
          Accept: 'application/json',
          Bearer: store.xToken,
        },
      },
    )
    .then((response) => {
      if (response.status == 200) {
        store.setModal({
          visible: true,
          message: 'Email de confirmación enviado',
          status: 'success',
          confirm: store.setModal({}),
        })
        setTimeout(() => {
          store.setModal({})
        }, 5000)
        emailSent.value = true
      }
    })
    .catch((err) => {
      store.setModal({
        visible: true,
        message: err.response?.data?.message,
        status: 'error',
        confirm: store.setModal({}),
      })
      setTimeout(() => {
        store.setModal({})
      }, 5000)
    })
}
</script>

<template>
  <div class="container">
    <template v-if="store.userLogged && (store.userLogged as any)?.email == null">
      <template v-if="!emailSent">
        <div>
          <p style="text-align: center">
            Tras la última actualización de la aplicación, se requiere que todos los usuarios registrados tengan una dirección de correo electrónico asociada
          </p>
          <p style="font-weight: bold; margin-top: 1rem; text-align: center">
            Por lo que deberás introducir un email válido en el formulario más abajo para seguir usando la app 👇 Muchas gracias
          </p>
          <Form
            :action="requestEmail"
            :error="error"
            submitValue="Enviar"
            :fields="[
              {
                name: 'email',
                placeholder: 'Correo electrónico',
                type: 'email',
                ref: emailRef,
                required: true,
              },
            ]"
          />
        </div>
      </template>
      <template v-else>
        <div>
          <p style="text-align: center">
            Revisa tu bandeja de entrada para confirmar tu correo.
          </p>
          <br />
          <p style="font-weight: bold; margin-top: 1rem; text-align: center">Si no lo encuentras, revisa la bandeja de correo no deseado.</p>
        </div>
      </template>
    </template>
    <template v-else>
      <div>
        <p style="text-align: center">
          Actualización correcta, serás redirigido a la app automáticamente
        </p>
        <br />
        <p style="font-weight: bold; margin-top: 1rem; text-align: center">Si no eres redirigido automáticamente, recarga la página</p>
      </div>
    </template>
  </div>
</template>
