// src/views/Room/Room.vue
<script setup lang="ts">
import { onMounted, computed } from 'vue'
import { useRouter } from 'vue-router'
import { useAppStore } from '../../stores/app'
import Classification from '../../components/ClassificationView/ClassificationView.vue'
import useNavigateWithCallback from '../../composables/useNavigateWithCallback'
import useValidateToken from '../../composables/useValidateToken'
import useHandleCloseSession from '../../composables/useHandleCloseSession'
import config from '../../config/config'

const store = useAppStore()
const router = useRouter()
const targetCount = computed(() => store.songs?.length > 5 ? 6 : 5)

onMounted(() => {
  if (!store.currentRoom?.current) {
    useNavigateWithCallback(router, '/app')
  }
})

onMounted(() => {
  if (
    (store.userLogged as any)?.email == null &&
    !window.location.href.includes(config.confirmemailLink)
  ) {
    useNavigateWithCallback(router, '/missing-email')
  } else if (
    (store.userLogged as any)?.countries?.length < targetCount.value &&
    (store.userLogged as any)?.countries != undefined
  ) {
    useNavigateWithCallback(router, '/country-select')
  }
})

onMounted(async () => {
  const isValidToken = await useValidateToken(store)
  if (!store.userLogged || !isValidToken) {
    useHandleCloseSession(store)
    if (window.location.pathname == '/join-room' || window.location.href.includes(config.confirmemailLink)) {
      useNavigateWithCallback(router, '/login?callback_url=' + window.location.href)
    } else {
      useNavigateWithCallback(router, '/login')
    }
  }
})
</script>

<template>
  <template v-if="(store.userLogged as any)?.countries?.length >= targetCount && store.currentRoom != undefined && store.currentRoom?.current != undefined">
    <div class="container">
      <Classification
        :room="store.currentRoom?.current"
        :animate="true"
      />
    </div>
  </template>
</template>

// src/Views/Room/Room.jsx
import React, { useContext, useEffect } from "react";
import AppContext from "../../Storage/AppContext";
import Classification from "../../Components/ClassificationView/Classification";
import useNavigateWithCallback from "../../utils/useNavigateWithCallback";
import { useNavigate } from "react-router-dom";
import useValidateToken from "../../utils/useValidateToken";
import useHandleCloseSession from "../../utils/useHandleCloseSession";
import config from "../../config/config";


const Room = () => {
	const context = useContext(AppContext);
	const navigate = useNavigate();

	const targetCount = context.songs?.length > 5 ? 6 : 5;
	useEffect(() => {
		if (!context.current_room?.current) {
			useNavigateWithCallback(navigate, "/app");
		}
		
	}, []);
	useEffect(() => {
		if (
			context.user_logged?.email == null &&
			!window.location.href.includes(config.confirmemailLink)
		) {
			useNavigateWithCallback(navigate, "/missing-email");
		} else if (
			context.user_logged?.countries?.length < targetCount &&
			context.user_logged?.countries != undefined
		) {
			useNavigateWithCallback(navigate, "/country-select");
		}
	}, [targetCount, context.user_logged]);
	
	useEffect(() => {
		async function validateUserToken() {
			const isValidToken = await useValidateToken(context);
			if (!context.user_logged || !isValidToken) {
				useHandleCloseSession(context);
				if (window.location.pathname == "/join-room" || window.location.href.includes(config.confirmemailLink)) {
					useNavigateWithCallback(navigate, "/login?callback_url=" + window.location.href);
				} else {
					useNavigateWithCallback(navigate, "/login");
				}
			}
		}
		validateUserToken();
	}, []);


	return (
		<>
			{context.user_logged.countries?.length >= targetCount &&
				context.current_room != undefined &&
				context.current_room?.current != undefined && (
					<div className="container">
						<Classification
							room={context.current_room?.current}
							animate={true}
						/>
					</div>
				)}
		</>
	);
};

export default Room;
