// src/Components/CountryPicker/CountryPicker.jsx
import { React, useState, useContext, useEffect } from "react";
import "./CountryPicker.Component.css";
import "/node_modules/flag-icons/css/flag-icons.min.css";
import Modal from "../Modal/Modal";
import { Link } from "react-router-dom";
import { GiPlayButton } from "react-icons/gi";
import { IconContext } from "react-icons";
import AppContext from "../../Storage/AppContext";
import axios from "axios";
import config from "../../config/config";
import useGetSongs from "../../utils/useGetSongs";
const CountryPicker = (props) => {
	const [continuar, setContinuar] = useState(false);
	const [songs, setSongs] = useState(props.countries);

	const context = useContext(AppContext);
	const targetCount = (songs && songs.length > 5) ? 6 : 5;

	useEffect(() => {
		setContinuar(context.selection.current.length == targetCount);
	}, [songs, context.selection.current.length]);

	async function handleContinue() {
		if (context.selection.current.length == targetCount) {
			const data = {
				userId: context.user_logged?.id,
				selection: context.selection.current,
			};
			await axios
				.post(`${config.baseUrl}users/bulk/add-country/`, data, {
					headers: {
						Accept: "application/json",
						Bearer: context.x_token,
					},
				})
				.then((response) => {
					if (response.status == 201) {
						context.setModal({
							visible: true,
							message: "Actualización correcta",
							status: "success",
							confirm: context.setModal({}),
						});
						setTimeout(() => {
							context.setModal({});
						}, 3000);
						context.setUserLogged((user) => ({
							...user,
							countries: context.selection.current,
						}));
					}
				})
				.catch((error) => {
					context.setModal({
						visible: true,
						message: error.response.data.message,
						status: "error",
						confirm: context.setModal({}),
					});
					setTimeout(() => {
						context.setModal({});
					}, 3000);

					return error;
				});
		} else {
			context.setModal({
				visible: true,
				message: `Tienes que elegir ${targetCount} países`,
				status: "error",
				confirm: context.setModal({}),
			});
			setTimeout(() => {
				context.setModal({});
			}, 3000);
		}
	}

	function validateSelection() {
		let elements = Array.from(document.getElementsByTagName("input"));
		if (context.selection.current.length == targetCount) {
			setContinuar(true);
			elements.map((element) => {
				if (!element.checked) {
					element.disabled = true;
					element.parentElement.parentElement.classList.add("disabled");
				}
			});
			return false;
		}
		setContinuar(false);
		elements.map((element) => {
			element.disabled = false;
			element.parentElement.parentElement.classList.remove("disabled");
		});
		return true;
	}

	function handleSelect(event) {
		let selectedCountriesTemp = context.selection.current;
		if (event.target.checked) {
			if (validateSelection()) {
				selectedCountriesTemp.push(parseInt(event.target.id));
			} else {
				context.setModal({
					visible: true,
					message: `No puedes elegir más de ${targetCount} países`,
					status: "error",
					confirm: context.setModal({}),
				});
				setTimeout(() => {
					context.setModal({});
				}, 3000);
			}
		} else {
			selectedCountriesTemp.splice(
				selectedCountriesTemp.indexOf(parseInt(event.target.id)),
				1
			);
		}

		context.setSelection((selection) => ({
			...selection,
			current: selectedCountriesTemp,
		}));
		validateSelection();
	}

		useEffect(() => {
			if (context.x_token) {
				initializeSongs();
			}
		}, []);
	
		useEffect(() => {
			context.setSongs(songs);
		}, [songs]);
		
	
		async function initializeSongs() {
			const songs = await useGetSongs(context);
			setSongs(songs);
		}
	return (
		<>
			<div className="countries-container">
				<p>
					Selecciona {targetCount} países de los siguientes, es importante que el primer
					país seleccionado sea el que creas que será el ganador, {targetCount == 6 && " el sexto seleccionado será tu apuesta para la última posición,"} podrás
					comprobarlo porque {targetCount == 6 ? "aparecerán resaltados" : "aparecerá resaltado"} respecto a los demás.
				</p>
				<div className="selected-countries-container">
					<p>Países seleccionados: </p>
					<div className="selected-countries">
						{context.selection.current.map((country) => {
							return (
								<p
									key={context.selection.current.indexOf(country)}
									className={
										context.selection.current.indexOf(country) == 0
											? "winner-country"
											: context.selection.current.indexOf(country) == 5
											? "last-country"
											: ""
									}
								>
									{songs && songs.find((element) => element.id == country).name}
								</p>
							);
						})}
					</div>
				</div>
				{continuar && (
					<div className="continue-container">
						<button type="button" onClick={handleContinue}>
							Continuar
						</button>
					</div>
				)}
				{songs && songs?.map((country) => {
					return (
						<article
							className={
								context.selection.current.includes(country.id)
									? "country-container country-selected-card"
									: "country-container"
							}
							key={songs?.indexOf(country)}
						>
							<label htmlFor={country.id}>
								<div className="country-info-container">
									<p>
										<span
											className={`fi fi-${country.code} fis country-flag-select`}
										></span>
										{country.name}
									</p>
									{country.link && <div className="song-link-container">
										<p className="song-container">
											{country.song.replace("amp;", "")}
										</p>
										<Link to={country.link} target="_blank" rel="noopener">
											<IconContext.Provider
												value={{ color: "rgb(255, 248, 0)", size: "20px" }}
											>
												<div className="header-icon-container">
													<GiPlayButton />
												</div>
											</IconContext.Provider>
										</Link>
									</div>}
								</div>
								<input
									type="checkbox"
									className="country-checkbox"
									onChange={handleSelect}
									name={country.name}
									defaultChecked={context.selection.current.includes(
										country.id
									)}
									id={country.id}
								/>
							</label>
						</article>
					);
				})}
			</div>
		</>
	);
};

export default CountryPicker;

// src/components/CountryPicker/CountryPicker.vue
<script setup lang="ts">
import { ref, computed, watch } from 'vue'
import { useAppStore } from '../../stores/app'
import { Icon } from '@iconify/vue'
import axios from 'axios'
import config from '../../config/config'

interface CountryPickerProps {
  modal?: boolean
  additionalAction?: () => void
}

const props = defineProps<CountryPickerProps>()
const store = useAppStore()

const songs = computed(() => store.songs)
const targetCount = computed(() => (songs.value?.length > 5 ? 6 : 5))
const continuar = ref(false)

watch(
  () => store.selection.current.length,
  () => {
    continuar.value = store.selection.current.length == targetCount.value
  },
)

async function handleContinue() {
  if (store.selection.current.length == targetCount.value) {
    const data = {
      userId: (store.userLogged as any)?.id,
      selection: store.selection.current,
    }
    try {
      const response = await axios.post(
        `${config.baseUrl}users/bulk/add-country/`,
        data,
        {
          headers: {
            Accept: 'application/json',
            Bearer: store.xToken,
          },
        },
      )
      if (response.status == 201) {
        store.setModal({
          visible: true,
          message: 'Actualización correcta',
          status: 'success',
          confirm: store.setModal({}),
        })
        setTimeout(() => {
          store.setModal({})
        }, 3000)
        store.setUserLogged({
          ...(store.userLogged as any),
          countries: store.selection.current,
        })
      }
    } catch (error: any) {
      store.setModal({
        visible: true,
        message: error.response?.data?.message,
        status: 'error',
        confirm: store.setModal({}),
      })
      setTimeout(() => {
        store.setModal({})
      }, 3000)
    }
    if (props.additionalAction) {
      props.additionalAction()
    }
  } else {
    store.setModal({
      visible: true,
      message: `Tienes que elegir ${targetCount.value} países`,
      status: 'error',
      confirm: store.setModal({}),
    })
    setTimeout(() => {
      store.setModal({})
    }, 3000)
  }
}

function validateSelection() {
  const elements = Array.from(document.getElementsByTagName('input'))
  if (store.selection.current.length == targetCount.value) {
    continuar.value = true
    elements.forEach((element) => {
      if (!element.checked) {
        element.disabled = true
        element.parentElement?.parentElement?.classList.add('disabled')
      }
    })
    return false
  }
  continuar.value = false
  elements.forEach((element) => {
    element.disabled = false
    element.parentElement?.parentElement?.classList.remove('disabled')
  })
  return true
}

function handleSelect(event: Event) {
  const target = event.target as HTMLInputElement
  const selectedCountriesTemp = [...store.selection.current]
  if (target.checked) {
    if (validateSelection()) {
      selectedCountriesTemp.push(parseInt(target.id))
      store.setSelection({ current: selectedCountriesTemp })
    } else {
      store.setModal({
        visible: true,
        message: `No puedes elegir más de ${targetCount.value} países`,
        status: 'error',
        confirm: store.setModal({}),
      })
      setTimeout(() => {
        store.setModal({})
      }, 3000)
    }
  } else {
    const index = selectedCountriesTemp.indexOf(parseInt(target.id))
    if (index > -1) {
      selectedCountriesTemp.splice(index, 1)
    }
    store.setSelection({ current: selectedCountriesTemp })
    validateSelection()
  }
}
</script>

<template>
  <div class="countries-container">
    <p>
      Selecciona {{ targetCount }} países de los siguientes, es importante que el primer
      país seleccionado sea el que creas que será el ganador, {{ targetCount == 6 ? ' el sexto seleccionado será tu apuesta para la última posición,' : '' }} podrás
      comprobarlo porque {{ targetCount == 6 ? 'aparecerán resaltados' : 'aparecerá resaltado' }} respecto a los demás.
    </p>
    <div class="selected-countries-container">
      <p>Países seleccionados: </p>
      <div class="selected-countries">
        <p
          v-for="(countryId, index) in store.selection.current"
          :key="index"
          :class="index == 0 ? 'winner-country' : index == 5 ? 'last-country' : ''"
        >
          {{ songs && songs.find((element: any) => element.id == countryId)?.name }}
        </p>
      </div>
    </div>
    <div v-if="continuar" class="continue-container">
      <button type="button" @click="handleContinue">
        Continuar
      </button>
    </div>
    <template v-if="songs">
      <article
        v-for="country in songs"
        :key="country.id"
        :class="
          store.selection.current.includes(country.id)
            ? 'country-container country-selected-card'
            : 'country-container'
        "
      >
        <label :for="country.id">
          <div class="country-info-container">
            <p>
              <span :class="`fi fi-${country.code} fis country-flag-select`"></span>
              {{ country.name }}
            </p>
            <div v-if="country.link" class="song-link-container">
              <p class="song-container">
                {{ country.song?.replace('amp;', '') }}
              </p>
              <a :href="country.link" target="_blank" rel="noopener">
                <div class="header-icon-container">
                  <Icon icon="mdi:play-circle" style="color: rgb(255, 248, 0); font-size: 20px;" />
                </div>
              </a>
            </div>
          </div>
          <input
            type="checkbox"
            class="country-checkbox"
            :name="country.name"
            :default-checked="store.selection.current.includes(country.id)"
            :id="country.id"
            @change="handleSelect"
          />
        </label>
      </article>
    </template>
  </div>
</template>

<style src="../../Components/CountryPicker/CountryPicker.Component.css"></style>
<style src="flag-icons/css/flag-icons.min.css"></style>
