// src/views/UserDetails/UserDetails.vue
<script setup lang="ts">
import { ref, onMounted, computed } from 'vue'
import { useRouter } from 'vue-router'
import { useAppStore } from '../../stores/app'
import CountryPicker from '../../components/CountryPicker/CountryPicker.vue'
import Collapsible from '../../components/Collapsible/Collapsible.vue'
import Form from '../../components/Form/Form.vue'
import axios from 'axios'
import { validateEmailRegex, validateRegex, validateUserNameRegex } from '../../utils/regexUtils'
import config from '../../config/config'
import useNavigateWithCallback from '../../composables/useNavigateWithCallback'
import useValidateToken from '../../composables/useValidateToken'
import useHandleCloseSession from '../../composables/useHandleCloseSession'

const store = useAppStore()
const router = useRouter()
const preview = ref<string | null>(null)
const error = ref<any>({})
const currentCollapsed = ref(false)
const passRef = ref<HTMLInputElement | null>(null)
const pass2Ref = ref<HTMLInputElement | null>(null)
const userNameRef = ref<HTMLInputElement | null>(null)
const emailRef = ref<HTMLInputElement | null>(null)
const colorRef = ref<HTMLInputElement | null>(null)
const imageRef = ref<HTMLInputElement | null>(null)

onMounted(async () => {
  const isValidToken = await useValidateToken(store)
  if (!store.userLogged || !isValidToken) {
    useHandleCloseSession(store)
    if (window.location.pathname == '/join-room' || window.location.href.includes(config.confirmemailLink)) {
      useNavigateWithCallback(router, '/login?callback_url=' + window.location.href)
    } else {
      useNavigateWithCallback(router, '/login')
    }
  }
  if ((store.userLogged as any)?.email == null && !window.location.href.includes(config.confirmemailLink)) {
    useNavigateWithCallback(router, '/missing-email')
  }
})

function handleCollapsed() {
  currentCollapsed.value = !currentCollapsed.value
}

async function updateUserData(event: Event, data: any) {
  await axios
    .put(
      `${config.baseUrl}users/${(store.userLogged as any)?.id}`,
      data,
      {
        headers: {
          Accept: 'application/json',
          Bearer: store.xToken,
        },
      },
    )
    .then((response) => {
      if (response.status == 200) {
        store.setModal({
          visible: true,
          message: 'Actualización correcta',
          status: 'success',
          confirm: store.setModal({}),
        })
        setTimeout(() => {
          store.setModal({})
        }, 5000)
        store.setUserLogged(response.data)
      }
    })
    .catch((error) => {
      store.setModal({
        visible: true,
        message: error.response?.data?.message,
        status: 'error',
        confirm: store.setModal({}),
      })
      setTimeout(() => {
        store.setModal({})
      }, 5000)
    })
}

function updateUserName(event: Event) {
  event.preventDefault()
  if (
    !validateUserNameRegex(userNameRef.value?.value || '', () =>
      error.value = {
        status: true,
        message: 'Nombre de usuario no válido, debe contener 5 a 25 caracteres, evita caracteres especiales',
      },
    )
  ) {
    return
  }
  updateUserData(event, { username: userNameRef.value?.value })
}

function updateEmail(event: Event) {
  event.preventDefault()
  if (
    !validateEmailRegex(emailRef.value?.value || '', () =>
      error.value = {
        status: true,
        message: 'Correo electrónico no válido',
      },
    )
  ) {
    return
  }
  updateUserData(event, { email: emailRef.value?.value })
}

function updatePassword(event: Event) {
  event.preventDefault()
  if (passRef.value?.value != pass2Ref.value?.value) {
    error.value = { status: true, message: 'Las contraseñas no coinciden' }
    return
  }
  if (
    !validateRegex(passRef.value?.value || '', () =>
      error.value = {
        status: true,
        message: 'Contraseña no válida, debe contener al menos 8 caracteres, incluyendo números y mayúscula',
      },
    )
  ) {
    return
  }
  updateUserData(event, { password: passRef.value!.value })
}

function handleImageChange(event: Event) {
  const target = event.target as HTMLInputElement
  if (target.files && target.files[0]) {
    preview.value = URL.createObjectURL(target.files[0])
  }
}

async function updateImage(event: Event) {
  event.preventDefault()
  if (!imageRef.value?.files?.[0]) return
  const formData = new FormData()
  formData.append('image', imageRef.value.files[0])
  updateUserData(event, formData)
}

function onImageChange(event: Event) {
  handleImageChange(event)
}
</script>

<template>
  <div class="details-container">
    <div class="section-one">
      <Collapsible :title="'Países seleccionados'" :collapsed="currentCollapsed" @toggle="handleCollapsed">
        <CountryPicker :countries="store.songs" :additionalAction="handleCollapsed" />
      </Collapsible>
    </div>

    <div class="section-two">
      <button class="delete-user-button">Eliminar cuenta</button>
    </div>
  </div>
</template>

<style src="../../Views/UserDetails/UserDetails.Component.css"></style>

// src/Views/UserDetails/UserDetails.jsx
import React, { useContext, useState, useEffect, useRef } from "react";
import "./UserDetails.Component.css";
import AppContext from "../../Storage/AppContext";
import CountryPicker from "../../Components/CountryPicker/CountryPicker";
import { useNavigate } from "react-router-dom";
import Collapsible from "../../Components/Collapsible/Collapsible";
import Modal from "../../Components/Modal/Modal";
import useValidateToken from "../../utils/useValidateToken";
import useHandleCloseSession from "../../utils/useHandleCloseSession";
import Form from "../../Components/Form/Form";
import axios from "axios";
import { validateEmailRegex, validateRegex, validateUserNameRegex } from "../../utils/regexUtils";
import bcrypt from "bcryptjs";
import config from "../../config/config";
import useNavigateWithCallback from "../../utils/useNavigateWithCallback";
 

const UserDetails = () => {
	const context = useContext(AppContext);
	const [preview, setPreview] = useState(null)
	const navigate = useNavigate();
	const [modal, setModal] = useState({});
	const [error, setError] = useState({});
	const [currentCollapsed, setcurrentCollapsed] = useState(false);

	useEffect(() => {
		async function validateUserToken() {
			const isValidToken = await useValidateToken(context);
			if (!context.user_logged || !isValidToken) {
				useHandleCloseSession(context);
				if (window.location.pathname == "/join-room" || window.location.href.includes(config.confirmemailLink)) {
					useNavigateWithCallback(navigate, "/login?callback_url=" + window.location.href);
				} else {
					useNavigateWithCallback(navigate, "/login");
				}
			}
		}
		validateUserToken();
	}, []);

	useEffect(() => {
		if (context.user_logged?.email == null && !window.location.href.includes(config.confirmemailLink)) {
			useNavigateWithCallback(navigate, "/missing-email");
		}
	}, [])
	
	const passRef = useRef(null);
	const pass2Ref = useRef(null);
	const userNameRef = useRef(null);
	const emailRef = useRef(null);
	const colorRef = useRef(null);
	const imageRef = useRef(null);
	let data;

	async function updateUserData(event, data) {
		await axios
			.put(
				`${config.baseUrl}users/${context.user_logged?.id}`,
				data,
				{
					headers: {
						Accept: "application/json",
						bearer: `${context.x_token}`,
					},
				}
			)
			.then((response) => {
				if (response.status == 200) {
					setModal({
						visible: true,
						message: "Actualización correcta",
						status: "success",
						confirm: setModal({}),
					});
					setTimeout(() => {
						setModal({});
					}, 5000);
					event.target.reset();
					context.setUserLogged(response.data);
				}
			})
			.catch((error) => {
				setModal({
					visible: true,
					message: error.response.data.message,
					status: "error",
					confirm: setModal({}),
				});
				setTimeout(() => {
					setModal({});
				}, 5000);
			});
	}

	function udpateUserEmail(event) {
		event.preventDefault();
		if (
			!validateEmailRegex(emailRef.current.value, () =>
				setError({
					status: true,
					message:
						"Correo electrónico no válido",
				})
			)
		) {
			return false;
		}
		setError(false);
		data = {
			email: emailRef.current.value,
		};
		updateUserData(event, data);
	}

	function updateUserName(event) {
		event.preventDefault();
		if (
			!validateUserNameRegex(userNameRef.current.value, () =>
				setError({
					status: true,
					message:
						"Nombre de usuario no válido, debe contener 5 a 25 caracteres, evita caracteres especiales",
				})
			)
		) {
			return false;
		}
		setError(false);
		data = {
			username: userNameRef.current.value,
		};
		updateUserData(event, data);
	}

	function updatePassword(event) {
		event.preventDefault();
		if (passRef.current.value != pass2Ref.current.value) {
			setError({ status: true, message: "Las contraseñas no coinciden" });
			return false;
		} else {
			setError({});
		}
		if (
			!validateRegex(pass2Ref.current.value, () =>
				setError({
					status: true,
					message:
						"Contraseña no válida, debe contener al menos 8 caracteres, incluyendo números y mayúscula",
				})
			)
		) {
			return false;
		} else {
			setError({});
		}
		const salt = bcrypt.genSaltSync(12);
		const pass = bcrypt.hashSync(passRef.current.value, salt, null);
		data = {
			password: pass,
		};

		updateUserData(event, data);
	}

	function updateColor(event) {
		event.preventDefault();
		data = {
			color: colorRef.current.value,
		};

		updateUserData(event, data);
	}

	function updateImage(event) {
		event.preventDefault();
		const formData = new FormData();
		formData.append("image", imageRef.current.files[0]);
		updateUserData(event, formData);
	}

	const handleImageChange = (event) => {
		
		const file = event.target.files[0];
		if (file) {
		  setPreview(URL.createObjectURL(file));
		  
		}
	  };

	function handleCollapsed(){
		setcurrentCollapsed(!currentCollapsed);
	}

	return (
		<div className="container details-container">
			<div className="section-one">
				<Collapsible title={"Cambiar nombre de usuario: "}>
					<Form
						action={updateUserName}
						error={error}
						submitValue="Enviar"
						fields={[
							{
								name: "nombreUsuario",
								placeholder: "Nombre de usuario",
								id: "nombreUsuario",
								type: "text",
								ref: userNameRef,
							},
						]}
					/>
				</Collapsible>

				<Collapsible title={"Cambiar correo electrónico: "}>
					<Form
						action={udpateUserEmail}
						error={error}
						submitValue="Enviar"
						fields={[
							{
								name: "emaiUsuario",
								placeholder: "Correo electrónico",
								id: "emaiUsuario",
								type: "email",
								ref: emailRef,
							},
						]}
					/>
				</Collapsible>

				<Collapsible title={"Cambiar contraseña: "}>
					<Form
						action={updatePassword}
						error={error}
						showPassword={true}
						submitValue="Enviar"
						fields={[
							{
								name: "passwordOne",
								placeholder: "Contraseña",
								id: "passwordOne",
								type: "password",
								ref: passRef,
							},
							{
								name: "passwordTwo",
								placeholder: "Repetir contraseña",
								id: "passwordTwo",
								type: "password",
								ref: pass2Ref,
							},
						]}
					/>
				</Collapsible>

				<Collapsible title={"Actualizar avatar: "}>
					<Form
						action={updateImage}
						error={error}
						submitValue="Enviar"
						fields={[
							{
								name: "profileImage",
								id: "profileImage",
								type: "file",
								ref: imageRef,
								
							},
							
						]}
						preview = {preview}
						onImageChange= {handleImageChange}
					/>
				</Collapsible>


				<Collapsible title={"Cambiar color de tarjeta"}>
					<Form
						action={updateColor}
						error={error}
						default={context.user_logged?.color}
						submitValue="Enviar"
						fields={[
							{
								name: "Color",
								placeholder: "Color",
								id: "colorField",
								type: "color",
								ref: colorRef,
							},
						]}
					/>
				</Collapsible>
				<Collapsible title={"Cambiar países seleccionados"} collapsed={currentCollapsed}>
					<CountryPicker countries={context.songs} additionalAction={handleCollapsed} />
				</Collapsible>
			</div>

			<div className="section-two">
				<button className="delete-user-button">Eliminar cuenta</button>
			</div>

			{modal.visible && !modal.confirm && (
				<Modal
					message={modal.message}
					status={modal.status}
					onclick={() => setModal({})}
				/>
			)}
		</div>
	);
};

export default UserDetails;
