// src/components/Navigation/Navigation.vue
<script setup lang="ts">
import { ref, computed } from 'vue'
import { useRouter } from 'vue-router'
import { useAppStore } from '../../stores/app'
import { Icon } from '@iconify/vue'
import AdminPanel from '../AdminPanel/AdminPanel.vue'
import useHandleCloseSession from '../../composables/useHandleCloseSession'
import axios from 'axios'
import config from '../../config/config'

const store = useAppStore()
const router = useRouter()

const userMenu = ref(false)
const adminPanel = ref(false)
const passwordRef = ref<HTMLInputElement | null>(null)
const error = ref<any>({})

const callbackUrl = computed(() => {
  if (window.location.href.includes('callback_url=') && window.location.href.includes(config.joinRoomLink)) {
    return '?callback_url=' + window.location.href.split('callback_url=')[1]
  }
  return ''
})

async function loginAdmin(event: Event) {
  event.preventDefault()
  const pass = passwordRef.value?.value || ''
  try {
    const response = await axios.post(`${config.baseUrl}updatable/verify-password`, {
      password: pass,
    }, {
      headers: {
        Accept: 'application/json',
        Bearer: store.xToken,
      },
    })
    if (response.status == 200) {
      store.setUpdatable(response.data)
      router.push('/admin')
    }
  } catch (err: any) {
    error.value = {
      status: true,
      message: err.response?.data?.message || 'Contraseña incorrecta',
    }
  }
  adminPanel.value = false
}

function handleMenu(event: Event) {
  event.preventDefault()
  userMenu.value = !userMenu.value
}

function handleMenuHome() {
  if (userMenu.value) {
    userMenu.value = false
  }
}

function handleClickProfile() {
  userMenu.value = !userMenu.value
}

function handleAdmin(event: Event) {
  event.preventDefault()
  adminPanel.value = true
  userMenu.value = false
}

function handleCloseSession() {
  userMenu.value = false
  useHandleCloseSession(store)
}

function handleLeaveRoom() {
  store.setCurrentRoom(undefined)
  userMenu.value = false
}
</script>

<template>
  <header class="header-container">
    <div class="header">
      <div class="home-container">
        <router-link :to="'/' + callbackUrl" class="header-text" @click="handleMenuHome">
          <div class="header-icon-container">
            <Icon icon="mdi:star" style="color: #FF0087; font-size: 40px;" />
            <p>EuroContest</p>
          </div>
        </router-link>
      </div>
      <template v-if="store.userLogged">
        <div class="profile-button-container">
          <button class="profile-button" @click="handleMenu">
            <img
              :src="(store.userLogged as any)?.image ? `${(store.userLogged as any)?.image}` : `${config.defProfilePicUrl}${(store.userLogged as any)?.username}`"
              alt="imagen de usuario"
            />
          </button>
        </div>
      </template>
    </div>
    <div :class="userMenu ? 'user-menu menu-visible' : 'user-menu'">
      <ul>
        <li>
          <router-link to="/profile" @click="handleClickProfile">
            Perfil
          </router-link>
        </li>
        <li v-if="(store.userLogged as any)?.username == config.appAdmin">
          <router-link to="/" @click="handleAdmin">
            Admin
          </router-link>
        </li>
        <li v-if="store.currentRoom?.current != undefined">
          <router-link to="/app" @click="handleLeaveRoom">
            Salir de la sala
          </router-link>
        </li>
        <li>
          <router-link to="/archive" @click="handleClickProfile">
            Histórico de resultados
          </router-link>
        </li>
        <li>
          <router-link to="/login" @click="handleCloseSession">
            Cerrar sesión
          </router-link>
        </li>
      </ul>
    </div>
    <AdminPanel
      v-if="adminPanel"
      :action="loginAdmin"
      :refer="passwordRef"
      :error="error"
      :close="() => (adminPanel = false)"
    />
  </header>
</template>

<style src="../../Components/Navigation/Navigation.component.css"></style>

// src/Components/Navigation/Navigation.jsx
import React, { useContext, useState, useRef, useEffect } from "react";
import { Link, useNavigate } from "react-router-dom";
import "./Navigation.component.css";
import { HiStar } from "react-icons/hi";
import { IconContext } from "react-icons";
import AppContext from "../../Storage/AppContext";
import useHandleCloseSession from "../../utils/useHandleCloseSession";
import AdminPanel from "../AdminPanel/AdminPanel";
import axios from "axios";
import bcrypt from "bcryptjs";
import config from "../../config/config";


const Navigation = () => {
	const [userMenu, setUserMenu] = useState(false);
	const context = useContext(AppContext);
	const [adminPanel, setAdminPanel] = useState(false);
	const passwordRef = useRef(null);
	const [error, setError] = useState({});
	const navigate = useNavigate();
	const [callbackUrl, setCallbackUrl] = useState('');
	useEffect(() => {
		if (window.location.href.includes("callback_url=") && window.location.href.includes(config.joinRoomLink)) {
			setCallbackUrl("?callback_url=" + window.location.href.split("callback_url=")[1]);
		}
	}, [window.location.href]);

	async function loginAdmin(event) {
		event.preventDefault();
		const pass = passwordRef.current.value;
	await axios
			.get(`${config.baseUrl}updatable`, {
				headers: {
					Accept: "application/json",
					Bearer: context.x_token,
				},
			})
			.then(async (response) => {
				if (response.status == 200) {
					if (
						pass == response.data.master_password ||
						bcrypt.compareSync(pass, response.data.master_password)
					) {
						await context.setUpdatable(response.data);
						navigate("/admin");
					} else {
						setError({
							status: true,
							message: "Contaseña incorrecta",
						});
					}
				}
			})
			.catch((error) => {
				setError({
					status: true,
					message: error.response.data.message || error,
				});
			});
		setAdminPanel(false);
	}

	function handleMenu(event) {
		event.preventDefault();
		setUserMenu(!userMenu);
	}

	function handleMenuHome() {
		if (userMenu) {
			setUserMenu(!userMenu);
		}
	}

	function handleClickProfile() {
		setUserMenu(!userMenu);
	}
	function handleAdmin(event) {
		event.preventDefault();
		setAdminPanel(true);
		setUserMenu(!userMenu);
	}

	function handleCloseSession() {
		setUserMenu(!userMenu);
		useHandleCloseSession(context);
	}

	function handleLeaveRoom() {
		context.setCurrentRoom(undefined);
		setUserMenu(!userMenu);
	}
	return (
		<header className="header-container">
			<div className="header">
				<div className="home-container">
					<Link to={"/" + callbackUrl} className="header-text" onClick={handleMenuHome}>
						<IconContext.Provider value={{ color: "#FF0087", size: "40px" }}>
							<div className="header-icon-container">
								<HiStar />
								<p>EuroContest</p>
							</div>
						</IconContext.Provider>
					</Link>
				</div>

				{context.user_logged && (
					<>
						<div className="profile-button-container">
							<button className="profile-button" onClick={handleMenu}>
								<img
									src={context.user_logged?.image ? `${context.user_logged?.image}` :
										`${config.defProfilePicUrl}${context.user_logged?.username}`}
									alt="imagen de usuario"
								/>
							</button>
						</div>
					</>
				)}
			</div>
			<div className={userMenu ? `user-menu menu-visible` : "user-menu"}>
				<ul>
					<li>
						<Link to={"/profile"} onClick={handleClickProfile}>
							Perfil
						</Link>
					</li>
					{context.user_logged.username == config.appAdmin && (
						<li>
							<Link to={"/"} onClick={handleAdmin}>
								Admin
							</Link>
						</li>
					)}
					{context.current_room?.current != undefined && (
						<li>
							<Link to={"/app"} onClick={handleLeaveRoom}>
								Salir de la sala
							</Link>
						</li>
					)}
					<li>
						<Link to={"/archive"} onClick={handleClickProfile}>
							Histórico de resultados
						</Link>
					</li>
					<li>
						<Link to={"/login"} onClick={handleCloseSession}>
							Cerrar sesión
						</Link>
					</li>
				</ul>
			</div>
			{adminPanel && (
				<AdminPanel
					action={loginAdmin}
					refer={passwordRef}
					error={error}
					close={() => setAdminPanel(false)}
				/>
			)}
		</header>
	);
};

export default Navigation;
