// src/Components/Modal/Modal.jsx
import React, { useEffect } from "react";
import PropTypes from "prop-types";

import "./Modal.component.css";

const Modal = (props) => {
  return (
    <div className="modal-container">
      <div
        className={
          props.status == "success"
            ? "modal success-modal"
            : props.status == "error"
              ? "modal error-modal"
              : props.component
                ? "modal modal-component"
                : "modal"
        }
      >
        <button
          className="modal-button"
          onClick={props.onclick && props.onclick}
        >
          <p>X</p>
        </button>
        {props.component ?? <>
          <p>{props.message}</p>
          {props.confirm && (
            <div className="modal-action-buttons">
              <button
                className="action-btn"
                onClick={props.onaccept && props.onaccept}
              >
                Aceptar
              </button>
              <button
                className="action-delete-btn"
                onClick={props.onclick && props.onclick}
              >
                Cancelar
              </button>
            </div>
          )}
        </>}
      </div>
    </div>
  );
};

Modal.propTypes = {
  props: PropTypes.object,
  onclick: PropTypes.func,
  onaccept: PropTypes.func,
  status: PropTypes.string,
  message: PropTypes.string,
  confirm: PropTypes.bool,
};

export default Modal;

// src/components/Modal/Modal.vue
<script setup lang="ts">

interface ModalProps {
  message?: string
  status?: string
  onclick?: () => void
  onaccept?: () => void
  confirm?: boolean
  component?: any
}

defineProps<ModalProps>()
</script>

<template>
  <div class="modal-container">
    <div
      :class="
        status == 'success'
          ? 'modal success-modal'
          : status == 'error'
            ? 'modal error-modal'
            : component
              ? 'modal modal-component'
              : 'modal'
      "
    >
      <button class="modal-button" @click="onclick && onclick()">
        <p>X</p>
      </button>
      <template v-if="!component">
        <p>{{ message }}</p>
        <div v-if="confirm" class="modal-action-buttons">
          <button class="action-btn" @click="onaccept && onaccept()">
            Aceptar
          </button>
          <button class="action-delete-btn" @click="onclick && onclick()">
            Cancelar
          </button>
        </div>
      </template>
      <component :is="component" v-if="component" />
    </div>
  </div>
</template>

<style src="../../Components/Modal/Modal.component.css"></style>
