// src/views/CreateRoom/CreateRoom.vue
<script setup lang="ts">
import { ref, onMounted } from 'vue'
import { useRouter } from 'vue-router'
import { useAppStore } from '../../stores/app'
import axios from 'axios'
import useValidateToken from '../../composables/useValidateToken'
import useHandleCloseSession from '../../composables/useHandleCloseSession'
import useUpdateUserData from '../../composables/useUpdateUserData'
import { validateRegex, validateUserNameRegex } from '../../utils/regexUtils'
import Form from '../../components/Form/Form.vue'
import config from '../../config/config'

const store = useAppStore()
const router = useRouter()
const passwordRef = ref<HTMLInputElement | null>(null)
const passwordTwodRef = ref<HTMLInputElement | null>(null)
const roomNameRef = ref<HTMLInputElement | null>(null)
const error = ref<any>(false)

onMounted(async () => {
  const isValidToken = await useValidateToken(store)
  if (!store.userLogged || !isValidToken) {
    useHandleCloseSession(store)
    router.push('/login')
  }
})

async function crearSala(event: Event) {
  event.preventDefault()

  if (!validateUserNameRegex(roomNameRef.value?.value || '')) {
    error.value = {
      status: true,
      message: 'Nombre de sala no válido',
    }
    return
  }

  if (passwordRef.value?.value !== passwordTwodRef.value?.value) {
    error.value = {
      status: true,
      message: 'Las contraseñas no coinciden',
    }
    return
  }

  if (
    !validateRegex(passwordRef.value?.value || '', () =>
      error.value = {
        status: true,
        message: 'Contraseña no válida, debe contener al menos 8 caracteres, incluyendo números y mayúscula',
      },
    )
  ) {
    return
  }

  const data = {
    name: roomNameRef.value?.value,
    password: passwordRef.value!.value,
    adminId: (store.userLogged as any)?.id,
  }

  await axios
    .post(`${config.baseUrl}rooms`, data, {
      headers: {
        Accept: 'application/json',
        Bearer: store.xToken,
      },
    })
    .then((response) => {
      if (response.status == 201) {
        useUpdateUserData(store, router)
      }
    })
    .catch((err) => {
      error.value = {
        status: true,
        message: err.response?.data?.message,
      }
    })
}
</script>

<template>
  <div class="container">
    <Form
      :action="crearSala"
      :error="error"
      :showPassword="true"
      submitValue="Crear Sala"
      :fields="[
        {
          name: 'username',
          placeholder: 'Nombre de sala',
          type: 'text',
          ref: roomNameRef,
          required: true,
        },
        {
          name: 'password',
          placeholder: 'Contraseña',
          type: 'password',
          id: 'passwordOne',
          ref: passwordRef,
          required: true,
        },
        {
          name: 'password2',
          placeholder: 'Repetir contraseña',
          id: 'passwordTwo',
          type: 'password',
          ref: passwordTwodRef,
          required: true,
        },
      ]"
    />
  </div>
</template>

<style src="../../Views/CreateRoom/CreateRoom.Component.css"></style>

// src/Views/CreateRoom/CreateRoom.jsx
import React, { useContext, useRef, useState, useEffect } from "react";
import "./CreateRoom.Component.css";
import AppContext from "../../Storage/AppContext";
import axios from "axios";
import useValidateToken from "../../utils/useValidateToken";
import useHandleCloseSession from "../../utils/useHandleCloseSession";
import updateUserData from "../../utils/useUpdateUserData";
import { useNavigate } from "react-router-dom";
import { validateRegex, validateUserNameRegex } from "../../utils/regexUtils";
import bcrypt from "bcryptjs";
import Form from "../../Components/Form/Form";
import config from "../../config/config";

 

const CreateRoom = () => {
	const context = useContext(AppContext);
	const passwordRef = useRef(null);
	const passwordTwodRef = useRef(null);
	const roomNameRef = useRef(null);
	const [error, setError] = useState(false);
	const navigate = useNavigate();

	useEffect(() => {
		if (!context.user_logged) {
			navigate("/login");
		}
		if (!useValidateToken(context.user_logged?.token)) {
			useHandleCloseSession(context);
		}
	}, []);
	useEffect(() => {
		useValidateToken(context.user_logged?.token);
	}, [context]);

	async function crearSala(event) {
		event.preventDefault();
		if (
			!validateUserNameRegex(roomNameRef.current.value, () =>
				setError({
					status: true,
					message:
						"Nombre de sala no válido, debe contener 5 a 25 caracteres, evita caracteres especiales",
				})
			)
		) {
			return false;
		}

		if (passwordRef.current.value != passwordTwodRef.current.value) {
			setError({ status: true, message: "Las contraseñas no coinciden" });
			return false;
		}
		if (
			!validateRegex(passwordRef.current.value, () =>
				setError({
					status: true,
					message:
						"Contraseña no válida, debe contener al menos 8 caracteres, incluyendo números y mayúscula",
				})
			)
		) {
			return false;
		}
		const salt = bcrypt.genSaltSync(12);
		const pass = bcrypt.hashSync(passwordRef.current.value, salt, null);
		const data = {
			name: roomNameRef.current.value,
			password: pass,
			adminId: context.user_logged.id,
		};
		axios
			.post(`${config.baseUrl}rooms`, data, {
				headers: {
					Accept: "application/json",
					Bearer: context.x_token,
				},
			})
			.then((response) => {
				if (response.status == 201) {
					updateUserData(context, navigate);
				} else {
					setError({
						status: true,
						message: response.data.message,
					});
				}
			})
			.catch((error) => {
				if (error.response.status == 409) {
					setError({
						status: true,
						message: "Este nombre de sala ya está registrado",
					});
				} else {
					setError({
						status: true,
						message: error.response.data.message,
					});
				}
			});
	}

	return (
		<div className="container">
			<Form
				action={crearSala}
				error={error}
				showPassword={true}
				submitValue="Crear Sala"
				fields={[
					{
						name: "username",
						placeholder: "Nombre de sala",
						type: "text",
						ref: roomNameRef,
					},
					{
						name: "password",
						placeholder: "Contraseña",
						type: "password",
						id: "passwordOne",
						ref: passwordRef,
					},
					{
						name: "password2",
						placeholder: "Repetir contraseña",
						id: "passwordTwo",
						type: "password",
						ref: passwordTwodRef,
					},
				]}
			/>
		</div>
	);
};

export default CreateRoom;
