// src/views/CountrySelection/CountrySelect.vue
<script setup lang="ts">
import { onMounted, computed, watch } from 'vue'
import { useRouter } from 'vue-router'
import { useAppStore } from '../../stores/app'
import CountryPicker from '../../components/CountryPicker/CountryPicker.vue'
import useValidateToken from '../../composables/useValidateToken'
import useNavigateWithCallback from '../../composables/useNavigateWithCallback'
import config from '../../config/config'
import useHandleCloseSession from '../../composables/useHandleCloseSession'

const store = useAppStore()
const router = useRouter()
const targetCount = computed(() => store.songs?.length > 5 ? 6 : 5)

onMounted(async () => {
  const isValidToken = await useValidateToken(store)
  if (!store.userLogged || !isValidToken) {
    useHandleCloseSession(store)
    useNavigateWithCallback(router, '/login')
  }
})

watch([() => store.userLogged, targetCount], () => {
  if ((store.userLogged as any)?.countries?.length >= targetCount.value) {
    if (
      window.location.href.includes('callback_url=') &&
      window.location.href.includes(config.joinRoomLink)
    ) {
      window.location.href = window.location.href.split('callback_url=')[1]
    } else {
      useNavigateWithCallback(router, '/app')
    }
  }
})
</script>

<template>
  <div class="container">
    <template v-if="(store.userLogged as any)?.countries?.length < targetCount || (store.userLogged as any)?.countries == undefined">
      <CountryPicker :modal="true" />
    </template>
  </div>
</template>

// src/Views/CountrySelection/CountrySelect.jsx
import React, { useContext, useEffect } from "react";
import AppContext from "../../Storage/AppContext";
import CountryPicker from "../../Components/CountryPicker/CountryPicker";
import { useNavigate } from "react-router-dom";
import useValidateToken from "../../utils/useValidateToken";
import useNavigateWithCallback from "../../utils/useNavigateWithCallback";
import config from "../../config/config";
import useHandleCloseSession from "../../utils/useHandleCloseSession";

const CountrySelect = () => {
  const context = useContext(AppContext);
  const navigate = useNavigate();

  const targetCount = context.songs?.length > 5 ? 6 : 5;

  useEffect(() => {
    async function validateUserToken() {
      const isValidToken = await useValidateToken(context);
      if (!context.user_logged || !isValidToken) {
        useHandleCloseSession(context);
        useNavigateWithCallback(navigate, "/login");
      }
    }
    validateUserToken();
  }, []);

  useEffect(() => {
    if (context.user_logged?.countries?.length >= targetCount) {
      if (
        window.location.href.includes("callback_url=") &&
        window.location.href.includes(config.joinRoomLink)
      ) {
        window.location.href = window.location.href.split("callback_url=")[1];
      } else {
        useNavigateWithCallback(navigate, "/app");
      }
    }
  }, [context.user_logged, targetCount]);

  return (
    <>
      <div className="container">
        {(context.user_logged.countries?.length < targetCount ||
          context.user_logged.countries == undefined) && (
          <CountryPicker modal />
        )}
      </div>
    </>
  );
};

export default CountrySelect;
