// src/Layout.jsx
import { useContext, useEffect, useRef, useState } from "react";
import { useNavigate } from "react-router-dom";
import Footer from "./Components/Footer/Footer";
import Navigation from "./Components/Navigation/Navigation";
import PropTypes from "prop-types";
import axios from "axios";
import AppContext from "./Storage/AppContext";
import config from "./config/config"
import useGetAuthToken from "./utils/useGetAuthToken.js";
import useNavigateWithCallback from "./utils/useNavigateWithCallback.js";
import useUpdateuserData from "./utils/useUpdateUserData.js"
import useValidateToken from "./utils/useValidateToken.js";
import useHandleCloseSession from "./utils/useHandleCloseSession.js";
import useValidateEmail from "./utils/useValidateEmail.js";
import Modal from "./Components/Modal/Modal";


function Layout({ children }) {
	const d = new Date();
	const context = useContext(AppContext);
	const intervalRef = useRef(null);
	const [modal, setModal] = useState({});
	const RoomIntervalRef = useRef(null);
	const navigate = useNavigate();
	async function updatePointRequest() {
		await axios
			.get(
				`${config.baseUrl}countries/refresh/${d.getFullYear()}`,
				{
					headers: {
						Accept: "application/json",
						Bearer: context.x_token,
					},
				}
			)
			.then((response) => {
				if (response.status == 200) {
					return response.data;
				} else if (response.status == 401) {
					useGetAuthToken(context);
					updatePointRequest();
				}
			})
			.catch((error) => {
				return error.response.data.message;
			});
	}
	useEffect(() => {
		if (context.x_token &&
			context.current_room?.current != undefined) {
			if (!RoomIntervalRef.current) {
				RoomIntervalRef.current = setInterval(() => {
					updateRoomData(context.current_room?.current?.id);
				}, 60000);
			}

		} else {
			clearInterval(RoomIntervalRef.current);
			RoomIntervalRef.current = null;
		}

	}, [context.current_room]);

	function updateRoomData(roomId) {
		axios
			.get(`${config.baseUrl}rooms/${roomId}`, {
				headers: {
					Accept: "application/json",
					Bearer: context.x_token,
				},
			})
			.then((response) => {
				if (response.status == 200) {
					if (context.current_room.current) {
						const userToUpdate = response.data.users.find(
							(element) => element.id == context.user_logged?.id
						);
						context.setUserLogged((user) => {
							return {
								...user,
								countries: userToUpdate.countries,
							};
						});
						context.setCurrentRoom((old) => ({
							...old,
							current: response.data,
						}));
					}
				}
			})
			.catch((error) => {
				if (error.response.status == 404) {
					return {
						status: true,
						message: "Sala no encontrada",
					};
				} else {
					return {
						status: true,
						message: error.response.data.message,
					};
				}
			});
	}

	useEffect(() => {
		async function getToken() {
			await useGetAuthToken(context);
		}
		getToken();
		if (!(context.user_logged?.token || useValidateToken(context.user_logged?.token))) {
			useHandleCloseSession(context);
			if (window.location.pathname == "/join-room") {
				useNavigateWithCallback(navigate, "/login?callback_url=" + window.location.href);
			} else {
				useNavigateWithCallback(navigate, "/login");
			}
		} else if (!context.user_logged?.email && !window.location.href.includes(config.confirmemailLink)) {
			navigate("/missing-email");
		} else if (context.user_logged?.countries?.length < 5) {
			context.setCurrentRoom(() => ({
			}));
			if (window.location.pathname == "/join-room") {
				useNavigateWithCallback(navigate, "/country-select?callback_url=" + window.location.href);
			} else {
				useNavigateWithCallback(navigate, "/country-select");
			}
		} else {
			if (window.location.href.includes("callback_url=") && window.location.href.includes(config.joinRoomLink)) {
				window.location.href = window.location.href.split("callback_url=")[1];
			}

			if (window.location.pathname == "/join-room") {
				handleJoinRoomLink();
			}
		}

	}, [context.user_logged]);

	useEffect(() => {
		useGetAuthToken(context);
		setInterval(() => useGetAuthToken(context), 1200000);
	}, []);

	useEffect(() => {
		if (
			context.x_token &&
			context.user_logged?.username === config.appAdmin &&
			context.updatable?.refresh_enabled
		) {
			intervalRef.current = setInterval(() => {
				updatePointRequest();
			}, 40000);
		} else {
			if (intervalRef.current) {
				clearInterval(intervalRef.current);
				intervalRef.current = null;
			}

		}
	}, [context.user_logged]);

	async function addUserRoom(data) {
		await axios
			.post(`${config.baseUrl}rooms/add-user`, data, {
				headers: {
					Accept: "application/json",
					Bearer: context.x_token,
				},
			})
			.then((response) => {
				if (response.status == 201) {
					useUpdateuserData(context, navigate);
				}
			})
			.catch(() => {
				navigate("/app");
			});
	}
	async function handleJoinRoomLink() {
		if (window.location.href.includes("roomAuth")) {
			const roomAuth = window.location.href.split("roomAuth=")[1];
			await axios.post(`${config.baseUrl}rooms/verifyRoomToken`, { token: roomAuth }, {
				headers: {
					Accept: "application/json",
					Bearer: context.x_token,
				},
			})
				.then((response) => {
					if (response.status == 200) {
						addUserRoom({
							userId: context.user_logged?.id,
							roomId: response.data.id,
						});
					}
				})
				.catch(async (error) => {
					if (error.response.status == 401) {
						await useGetAuthToken(context);
						handleJoinRoomLink();
					}
					navigate("/app");
				});
		}
	}

	return (
		<>
			<Navigation />
			{children}
			{modal.visible && !modal.confirm && (
				<Modal
					message={modal.message}
					status={modal.status}
					onclick={() => setModal({})}
				/>
			)}
			<Footer />
		</>
	);
}

Layout.propTypes = {
	children: PropTypes.node.isRequired,
};

export default Layout;

// src/Layout.vue
<script setup lang="ts">
import { ref, computed, onMounted, onUnmounted, watch } from 'vue'
import { useRoute, useRouter } from 'vue-router'
import { useAppStore } from './stores/app'
import axios from 'axios'
import config from './config/config'
import useUpdateUserData from './composables/useUpdateUserData'
import useNavigateWithCallback from './composables/useNavigateWithCallback'
import Navigation from './components/Navigation/Navigation.vue'
import Footer from './components/Footer/Footer.vue'
import Modal from './components/Modal/Modal.vue'

const store = useAppStore()
const router = useRouter()
const route = useRoute()

const d = new Date()
const intervalRef = ref<ReturnType<typeof setInterval> | null>(null)
const roomIntervalRef = ref<ReturnType<typeof setInterval> | null>(null)

const modal = computed(() => store.modal)

function updatePointRequest() {
  axios
    .get(`${config.baseUrl}countries/refresh/${d.getFullYear()}`, {
      headers: {
        Accept: 'application/json',
        Bearer: store.xToken,
      },
    })
    .then((response) => {
      if (response.status == 200) {
        return response.data
      }
    })
    .catch((error) => {
      return error.response?.data?.message
    })
}

function updateRoomData(roomId: string) {
  axios
    .get(`${config.baseUrl}rooms/${roomId}/${(store.userLogged as any)?.id}`, {
      headers: {
        Accept: 'application/json',
        Bearer: store.xToken,
      },
    })
    .then((response) => {
      if (response.status == 200) {
        if (store.currentRoom?.current) {
          const userToUpdate = response.data.users.find(
            (element: any) => element.id == (store.userLogged as any)?.id,
          )
          store.setUserLogged({
            ...(store.userLogged as any),
            countries: userToUpdate.countries,
          })
          store.setCurrentRoom({
            ...store.currentRoom,
            current: response.data,
          })
        }
      }
    })
    .catch((error) => {
      if (error.response?.status == 404) {
        return { status: true, message: 'Sala no encontrada' }
      } else {
        return { status: true, message: error.response?.data?.message }
      }
    })
}

async function handleJoinRoomLink() {
  if (window.location.href.includes('roomAuth')) {
    const roomAuth = window.location.href.split('roomAuth=')[1]
    try {
      const response = await axios.post(
        `${config.baseUrl}rooms/verifyRoomToken/${(store.userLogged as any)?.id}`,
        { token: roomAuth },
        {
          headers: {
            Accept: 'application/json',
            Bearer: store.xToken,
          },
        },
      )
      if (response.status == 201) {
        useUpdateUserData(store, router)
        store.setModal({
          visible: true,
          message: 'Actualización correcta',
          status: 'success',
          confirm: store.setModal({}),
        })
        setTimeout(() => {
          store.setModal({})
        }, 5000)
      }
    } catch (error: any) {
      store.setModal({
        visible: true,
        message: error.response?.data?.message,
        status: 'error',
        confirm: store.setModal({}),
      })
      setTimeout(() => {
        store.setModal({})
      }, 5000)
      router.push('/app')
    }
  }
}

// Poll: refresh countries for admin
watch(
  () => store.userLogged,
  () => {
    if (
      store.xToken &&
      (store.userLogged as any)?.username === config.appAdmin &&
      store.updatable?.refresh_enabled
    ) {
      if (intervalRef.value) clearInterval(intervalRef.value)
      intervalRef.value = setInterval(() => {
        updatePointRequest()
      }, 40000)
    } else {
      if (intervalRef.value) {
        clearInterval(intervalRef.value)
        intervalRef.value = null
      }
    }
  },
  { deep: true },
)

// Poll: room data
watch(
  () => store.currentRoom,
  () => {
    if (store.xToken && store.currentRoom?.current != undefined) {
      if (!roomIntervalRef.value) {
        roomIntervalRef.value = setInterval(() => {
          updateRoomData(store.currentRoom?.current?.id)
        }, 60000)
      }
    } else {
      if (roomIntervalRef.value) {
        clearInterval(roomIntervalRef.value)
        roomIntervalRef.value = null
      }
    }
  },
  { deep: true },
)

// User auth and join-room link handling
watch(
  () => store.userLogged,
  () => {
    if (
      store.userLogged &&
      (store.userLogged as any)?.email != null &&
      (store.userLogged as any)?.countries?.length ==
        (store.songs?.length > 5 ? 6 : 5) &&
      window.location.pathname == '/join-room'
    ) {
      handleJoinRoomLink()
    }
    if (!store.userLogged) {
      if (
        window.location.href.includes('/join-room') ||
        window.location.href.includes(config.confirmemailLink)
      ) {
        useNavigateWithCallback(router, '/login?callback_url=' + window.location.href)
      } else {
        useNavigateWithCallback(router, '/login')
      }
    }
  },
)

onMounted(() => {
  // Initial room poll setup
  if (store.xToken && store.currentRoom?.current != undefined) {
    roomIntervalRef.value = setInterval(() => {
      updateRoomData(store.currentRoom?.current?.id)
    }, 60000)
  }
})

onUnmounted(() => {
  if (intervalRef.value) clearInterval(intervalRef.value)
  if (roomIntervalRef.value) clearInterval(roomIntervalRef.value)
})
</script>

<template>
  <div>
    <Navigation />
    <RouterView v-slot="{ Component }">
      <Suspense>
        <template #default>
          <component :is="Component" />
        </template>
        <template #fallback>
          <p>Loading...</p>
        </template>
      </Suspense>
    </RouterView>
    <!-- Confirm dialog -->
    <Modal
      v-if="modal.visible && modal.confirm && !modal.component"
      :message="modal.message"
      :status="modal.status"
      :onaccept="modal.onaccept"
      :confirm="true"
      :onclick="() => store.setModal({})"
    />
    <!-- Custom component modal -->
    <Modal
      v-if="modal.visible && modal.component"
      :onclick="modal.onclick"
      :onaccept="modal.onaccept"
      :message="modal.message"
      :component="modal.component"
    />
    <!-- Plain message modal -->
    <Modal
      v-if="modal.visible && !modal.confirm && !modal.component"
      :message="modal.message"
      :status="modal.status"
      :onclick="() => store.setModal({})"
    />
    <Footer />
  </div>
</template>
