// src/views/Archive/Archive.vue
<script setup lang="ts">
import { ref, onMounted } from 'vue'
import { useRouter } from 'vue-router'
import { useAppStore } from '../../stores/app'
import axios from 'axios'
import Classification from '../../components/ClassificationView/ClassificationView.vue'
import config from '../../config/config'
import useNavigateWithCallback from '../../composables/useNavigateWithCallback'
import useValidateToken from '../../composables/useValidateToken'
import useHandleCloseSession from '../../composables/useHandleCloseSession'

const store = useAppStore()
const router = useRouter()
const historicalRooms = ref<any>(false)
const selectedHistoricalRoom = ref<any>(false)
const loading = ref(true)

onMounted(async () => {
  const isValidToken = await useValidateToken(store)
  if (!store.userLogged || !isValidToken) {
    useHandleCloseSession(store)
    useNavigateWithCallback(router, '/login')
  }
  if ((store.userLogged as any)?.email == null && !window.location.href.includes(config.confirmemailLink)) {
    useNavigateWithCallback(router, '/missing-email')
  }
  await fetchRooms()
})

async function setSelectedRoom(roomId: string) {
  if (roomId) {
    try {
      const response = await axios.get(
        `${config.baseUrl}archive/room/${roomId}/${(store.userLogged as any)?.id}`,
        {
          headers: {
            Accept: 'application/json',
            Bearer: store.xToken,
          },
        },
      )
      if (response.status == 200) {
        selectedHistoricalRoom.value = response.data
      }
    } catch (error: any) {
      if (error.response?.status == 404) {
        return {
          status: true,
          message: 'No se han encontrado datos',
        }
      } else {
        return {
          status: true,
          message: error.response?.data?.message,
        }
      }
    }
  } else {
    selectedHistoricalRoom.value = false
  }
}

async function fetchRooms() {
  try {
    const response = await axios.get(
      `${config.baseUrl}archive/users/${(store.userLogged as any)?.id}`,
      {
        headers: {
          Accept: 'application/json',
          Bearer: store.xToken,
        },
      },
    )
    if (response.status == 200) {
      historicalRooms.value = response.data
    }
  } catch (error: any) {
    if (error.response?.status == 404) {
      return {
        status: true,
        message: 'No se han encontrado datos',
      }
    } else {
      return {
        status: true,
        message: error.response?.data?.message,
      }
    }
  } finally {
    loading.value = false
  }
}
</script>

<template>
  <div class="container">
    <template v-if="loading">
      <p class="archive-element">Obteniendo datos...</p>
    </template>
    <template v-else-if="historicalRooms">
      <template v-if="selectedHistoricalRoom">
        <select
          @change="(e: Event) => setSelectedRoom((e.target as HTMLSelectElement).value)"
          class="select-css selected"
        >
          <option value="">Selecciona una sala</option>
          <option
            v-for="room in historicalRooms"
            :key="room._id"
            :value="room._id"
            :id="room._id"
          >
            {{ room.room.name }} - {{ room.year }}
          </option>
        </select>
        <Classification :room="selectedHistoricalRoom" :animate="false" />
      </template>
      <template v-else>
        <select @change="(e: Event) => setSelectedRoom((e.target as HTMLSelectElement).value)" class="select-css">
          <option value="">Selecciona una sala</option>
          <option
            v-for="room in historicalRooms"
            :key="room._id"
            :value="room._id"
            :id="room._id"
          >
            {{ room.room.name }} - {{ room.year }}
          </option>
        </select>
      </template>
    </template>
    <template v-else>
      <p>No se han encontrado resultados históricos para el usuario</p>
    </template>
  </div>
</template>

<style src="../../Views/App/Home.Component.css"></style>

// src/Views/Archive/Archive.jsx
import React, { useContext, useEffect, useState } from "react";
import "../App/Home.Component.css";
import AppContext from "../../Storage/AppContext";
import { useNavigate } from "react-router-dom";
import axios from "axios";
import Classification from "../../Components/ClassificationView/Classification";
import config from "../../config/config";
import useNavigateWithCallback from "../../utils/useNavigateWithCallback";
import useValidateToken from "../../utils/useValidateToken";
import useHandleCloseSession from "../../utils/useHandleCloseSession";


const Archive = () => {
	const context = useContext(AppContext);
	const [historicalRooms, setHistoricalRooms] = useState(false);
	const navigate = useNavigate();
	const [selectedHistoricalRoom, setSelectedHistoricalRoom] = useState(false);
	const [loading, setLoading] = useState(true);

	useEffect(() => {
		fetchRooms();


	}, []);
	useEffect(() => {
		if (historicalRooms) {
			setLoading(false)
		}

	}, [historicalRooms])

	useEffect(() => {
		async function validateUserToken() {
			const isValidToken = await useValidateToken(context);
			if (!context.user_logged || !isValidToken) {
				useHandleCloseSession(context);
				useNavigateWithCallback(navigate, "/login");

			}
		}
		validateUserToken();
	}, []);
	useEffect(() => {
		if (context.user_logged?.email == null && !window.location.href.includes(config.confirmemailLink)) {
			useNavigateWithCallback(navigate, "/missing-email");
		}
	}, [])


	async function setSelectedRoom(roomId) {
		if (roomId) {
			await axios
				.get(`${config.baseUrl}archive/room/${roomId}/${context.user_logged?.id}`, {
					headers: {
						Accept: "application/json",
						Bearer: context.x_token,
					},
				})
				.then((response) => {
					if (response.status == 200) {
						setSelectedHistoricalRoom(response.data);
					}
				})
				.catch((error) => {
					if (error.response.status == 404) {
						return {
							status: true,
							message: "No se han encontrado datos",
						};
					} else {
						return {
							status: true,
							message: error.response.data.message,
						};
					}
				});
		} else {
			setSelectedHistoricalRoom(false)
		}

	}

	async function fetchRooms() {
		await axios
			.get(`${config.baseUrl}archive/users/${context.user_logged?.id}`, {
				headers: {
					Accept: "application/json",
					Bearer: context.x_token,
				},
			})
			.then((response) => {
				if (response.status == 200) {
					setHistoricalRooms(response.data);
				}
			})
			.catch((error) => {
				if (error.response.status == 404) {
					return {
						status: true,
						message: "No se han encontrado datos",
					};
				} else {
					return {
						status: true,
						message: error.response.data.message,
					};
				}
			});
	}

	return (
		<>
			<div className="container">
				{loading ? <p className="archive-element">Obteniendo datos...</p> : historicalRooms ?
					selectedHistoricalRoom ? (
						<>
							<select
								onChange={(e) => setSelectedRoom(e.target.value)}
								className="select-css selected"
							>
								<option value="">Selecciona una sala</option>
								{historicalRooms.map((room) => (
									<option key={room._id} value={room._id} id={room._id}>
										{room.room.name} - {room.year}
									</option>
								))}
							</select>
							<Classification
								room={selectedHistoricalRoom}
							/>
						</>


					) : (
						//A select element with all the rooms in the array
						<select
							onChange={(e) => setSelectedRoom(e.target.value)}
							className="select-css"
						>
							<option value="">Selecciona una sala</option>
							{historicalRooms.map((room) => (
								<option key={room._id} value={room._id} id={room._id}>
									{room.room.name} - {room.year}
								</option>
							))}
						</select>
					) : <p>No se han encontrado resultados históricos para el usuario</p>}
			</div>
		</>
	);
};

export default Archive;
